### ISSUE TITLE
Pangenome sequence analysis using the python script

### ISSUE THREAD

**Issue by slq356** [microgenomics/tutorials#2]
Have anyone ever had a problem with the python script, which takes the sequences from the .ffn files from Prokka into the analysis results from Roary?
Ive used the script from: https://github.com/EnzoAndree/tutorials/blob/patch-1/DBGenerator.py
The three first parts of the script works fine and makes three .csv files. But the "get_locus_sequence" does not, and produces a empty table. Ive have tried with different number of sequences and with the demo set without any luck.
Anyone knows anything?

**Comment by ecastron** [comment]
Dear @slq356,

Do you have a file that would reproduce the error? 

Thanks

@ecastron

**Comment by EnzoAndree** [comment]
Helo  @slq356, did you see any error when you run the script?

By the way, the function get_locus_sequence need the files locus_sequence.csv and genomas_locus.csv. did this files correctly generated?

Thanks
@EnzoAndree

**Comment by slq356** [comment]
@EnzoAndree, yes, the three other csv files are made with tables. If they are made correctly, i can not tell I have attached the csv-file.zip with the csv output files 
[csv-files.zip](https://github.com/microgenomics/tutorials/files/522644/csv-files.zip)
@ecastron, i have attached the test.zip with the .ffn files produced by prokka, the gene_presence_absence.csv file made by Roary and the DBGenerator.py script ive used. I had no errors, just nothing in the get_locus_sequence.csv.file
[test.zip](https://github.com/microgenomics/tutorials/files/522637/test.zip)

**Comment by ecastron** [comment]
Dear @slq356 

We tried your files and it worked just fine. Please check the steps we took in order to produce the attached output

From the Terminal create a directory `mkdir demo_github`, then copy your test.zip file to the newly created directory, `cp test.zip demo_github`. Then, change directory to demo_github and unzip test.zip by issuing the following commands `cd demo_github` and `unzip test.zip`. Finally, create a directory, move all .ffn files inside it, and execute the DBGenerator.py script: 

```
 mkdir ffn
 mv *.ffn ffn/
 python3 DBGenerator.py ffn
```

You should obtain [this output](https://www.dropbox.com/s/u2lk6fayj7vs4a9/demo_github.zip?dl=0).

Cheers,

@ecastron

**Comment by slq356** [comment]
ive just tried to do everything in the terminal, still with an empty locus_sequence file. Could it be the python version or what do you think?

**Comment by slq356** [comment]
okay i had it working now.
I dont know why, but i have to put in the ffn files in the .ffn folder, run the script. This gives the empty file. Afterwards i have to rename the the .ffn folder to ffn (not hidden) and run the script again - then it works?!?! I just dont understand?! anyways, it works now - thanks for the help

**Comment by ecastron** [comment]
Glad you got it running. I don't know though why you had a hidden folder? As I mentioned in the previous message, you have to move the ffn files inside the ffn folder and then execute the script. The script uses python 3.

**Comment by slq356** [comment]
Hey again. Now im starting to get this error when running 20+ sequences: 
Starting get_pangenoma
Starting get_genomas_locus
Starting get_pangenoma_locus
END get_pangenoma
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(_self._args, *_self._kwargs)
  File "DBGenerator.py", line 21, in get_genomas_locus
    for locus in loci:  # separalos!
NameError: name 'loci' is not defined
Starting get_locus_sequence
END get_locus_sequence
END get_pangenoma_locus

Any thoughts?

**Comment by jcm88** [comment]
Hey, was this resolved at all? I'm getting almost the exact same error:

Starting get_pangenoma
Starting get_genomas_locus
Starting get_pangenoma_locus
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/share/python-3.5.0/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/share/python-3.5.0/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/pub46/jmoran/bin/DBGenerator.py", line 24, in get_genomas_locus
    for locus in loci:  # separalos!
NameError: name 'loci' is not defined
Starting get_locus_sequence
END get_pangenoma
['GCA_000722505', 'ATGAGTGCCTTTGATGAAGAGATTGAAATTGAAATTGATGAGATATTCAAAAAAAGTAATAATTTTGGATATGATTTAAAAACAATATTTAGATAA']
Process Process-4:
Traceback (most recent call last):
  File "/usr/local/share/python-3.5.0/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/share/python-3.5.0/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/pub46/jmoran/bin/DBGenerator.py", line 112, in get_locus_sequence
    raise
RuntimeError: No active exception to reraise
END get_pangenoma_locus

genomas_locus, pangenoma and pangenoma_locus all contain what they should (as far as I can tell) but locus_sequence.csv is empty.

Any help would be hugely appreciated

**Comment by EnzoAndree** [comment]
Hello @slq356 

I've modified the script a little bit, although I'm not sure if I fixed the problem, you could try running with this new script.

if it's not fixed, maybe you could upload the files to reproduce the error.

Thanks

[DBGenerator.py.zip](https://github.com/microgenomics/tutorials/files/1736919/DBGenerator.py.zip)

**Comment by jcm88** [comment]
Hi @EnzoAndree different message output with that script version (no obvious error) but the locus_sequence.csv is still empty.

stdout:
Starting get_pangenoma
Starting get_pangenoma_locus
Starting get_genomas_locus
END get_pangenoma
END get_genomas_locus
Starting get_locus_sequence
['GCA_002088475', 'ATGGAAGAAAACCTTGCGATAAAACAAAAGGCTTATATTATTCTGGGTTCTTTTCTGGTTGCCGCATTTATTATTGGTATTGCCGGTGCATTGCAGGCACCGACACTCAGCCGTTATCTTGCCGAAGATGTGAAGGTTAACCCATATCAGGTAGGTTTGTTTTACTCAATCAATGCCGTTGCCGGCATTGTCGTCAGCTTTCTGCTGGCACAATATTCAGATAATAAAGGCGTTCGACGGAATATTATTCTATTTTGTTGTCTGATGGGCATAGGAAATTGCATTACATTTGCATTTTCGCGCCAATACTTTATCCTCGTTACCGTAGGCATATTTTTTTCAGCTTTTACCTCTGCAGCTATGCCGCAAATTTTTGCATCTGCACGTGAATATACAGATAAAACCGGCCGCAACGTTGTCGTTTTCAATGGCATTTTACGGGCGCAATTGTCACTGGCCTGGGTAATCGGTCCGCCATTATCATTTGCATTAGCCGTGAATTACGGATTTACCATTATGTATCTGAGTGCGGCAGCTATGTTTTTTGTAGCCATGCTGATCGTTTTTCTGTGCTTTCCTGTCATAAAACGTCCGGCATCTGTTACTAAAAAACAAGAGCCAAAAGAAAAGATTTTCAATAATCCTAATGTCATTTTGCTGTTTATCGCTTCAATCAGTATGGGTACAGCCAATATGATGTATTTGATTGATATGCCTTTATATATTGATGATATTTTGCCCGGTTCACCTTCACTGCCCGGACATTTGATGGGCATAGCTGCTGCCATTGAAATTCCCGCTATGCTGATTGCCAGCATGCTGGTACCGCGCTTTGGTAATAAAAATCTGATTTGTTTTGCAGTCATTTGCGGCATCATATTTTATATCGGTATGGTTTCGACCCAAAACGAATGGATGCTGATTGGTTTACAATTCTTTAATGGTTTATTTATCGGCATAATAGCCAGTATCGGTCTGATTTATTTTCAGGATTTATTACCTAAACGTACGGGTGTTGCTTCTACATTGTTTAATAACTGTATTTCTAGCAGTATTATTCTGGCCGGTATGTTGCAGGGTGTTATTTCGGCCAACTTCGGCCATCAGAGTATCTATACCATTTCTTTAGCCATGGTAATTTTATCTTTCATCTTGTGCCTGATTATTCAGCCACCGCCTTCAACAATTAAATTGCCCTCAAAGGTTAATCACTGA']
Process Process-4:
Traceback (most recent call last):
  File "/usr/local/share/python-3.5.0/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/share/python-3.5.0/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/pub46/jmoran/bin/DBGenerator.py", line 112, in get_locus_sequence
    raise
RuntimeError: No active exception to reraise
END get_pangenoma_locus

I've attached the files I've been using, the ffns were in there own folder, but even compressed this was too large to attach.

Thanks


[gene_presence_absence.csv.zip](https://github.com/microgenomics/tutorials/files/1737013/gene_presence_absence.csv.zip)

[GCA_000722505.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737030/GCA_000722505.1.ffn.gz)
[GCA_000725145.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737031/GCA_000725145.1.ffn.gz)
[GCA_000725185.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737032/GCA_000725185.1.ffn.gz)
[GCA_000725195.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737033/GCA_000725195.1.ffn.gz)
[GCA_002019415.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737034/GCA_002019415.1.ffn.gz)
[GCA_002088395.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737035/GCA_002088395.1.ffn.gz)
[GCA_002088405.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737036/GCA_002088405.1.ffn.gz)
[GCA_002088415.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737037/GCA_002088415.1.ffn.gz)
[GCA_002088455.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737038/GCA_002088455.1.ffn.gz)
[GCA_002088465.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737039/GCA_002088465.1.ffn.gz)
[GCA_002088475.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737040/GCA_002088475.1.ffn.gz)
[GCA_002088515.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737041/GCA_002088515.1.ffn.gz)
[GCA_002088525.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737042/GCA_002088525.1.ffn.gz)
[GCA_002088555.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737043/GCA_002088555.1.ffn.gz)
[GCA_002088575.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737044/GCA_002088575.1.ffn.gz)
[GCA_002088585.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737045/GCA_002088585.1.ffn.gz)
[GCA_002088595.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737046/GCA_002088595.1.ffn.gz)
[GCA_002088635.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737047/GCA_002088635.1.ffn.gz)
[GCA_002088655.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737048/GCA_002088655.1.ffn.gz)
[GCA_002088665.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737049/GCA_002088665.1.ffn.gz)
[GCA_002088675.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737050/GCA_002088675.1.ffn.gz)
[GCA_002088695.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737051/GCA_002088695.1.ffn.gz)
[GCA_002088735.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737052/GCA_002088735.1.ffn.gz)
[GCA_002088755.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737053/GCA_002088755.1.ffn.gz)
[GCA_002088765.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737054/GCA_002088765.1.ffn.gz)
[GCA_002089015.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737055/GCA_002089015.1.ffn.gz)
[GCA_002777315.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737056/GCA_002777315.1.ffn.gz)
[GCA_002777325.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737057/GCA_002777325.1.ffn.gz)
[GCA_002777335.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737058/GCA_002777335.1.ffn.gz)
[GCA_002777345.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737059/GCA_002777345.1.ffn.gz)
[GCA_002777415.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737060/GCA_002777415.1.ffn.gz)
[GCA_002777425.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737061/GCA_002777425.1.ffn.gz)
[GCA_002777465.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737062/GCA_002777465.1.ffn.gz)
[GCA_002777485.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737063/GCA_002777485.1.ffn.gz)
[GCA_002777495.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737064/GCA_002777495.1.ffn.gz)
[GCA_002777525.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737066/GCA_002777525.1.ffn.gz)
[GCA_002777575.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737067/GCA_002777575.1.ffn.gz)
[GCA_002777595.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737068/GCA_002777595.1.ffn.gz)
[GCA_002777615.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737069/GCA_002777615.1.ffn.gz)
[GCA_002777635.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737070/GCA_002777635.1.ffn.gz)
[GCA_002777655.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737071/GCA_002777655.1.ffn.gz)
[GCA_002777675.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737072/GCA_002777675.1.ffn.gz)
[GCA_002777695.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737073/GCA_002777695.1.ffn.gz)
[GCA_002777705.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737074/GCA_002777705.1.ffn.gz)
[GCA_002777735.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737075/GCA_002777735.1.ffn.gz)
[GCA_002777745.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737076/GCA_002777745.1.ffn.gz)
[GCA_002777775.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737077/GCA_002777775.1.ffn.gz)
[GCA_002777795.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737078/GCA_002777795.1.ffn.gz)
[GCA_002777815.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737079/GCA_002777815.1.ffn.gz)
[GCA_002777825.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737080/GCA_002777825.1.ffn.gz)
[GCA_002777855.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737081/GCA_002777855.1.ffn.gz)
[GCF_000600005.1.ffn.gz](https://github.com/microgenomics/tutorials/files/1737082/GCF_000600005.1.ffn.gz)
