### ISSUE TITLE
Pangenome sequence analysis

### ISSUE THREAD

**Issue by LilithElina** [microgenomics/tutorials#4]
Hello,

I've started working with the DBGenerator.py script a few days ago. It's a great help for me, and I got it to work with Python 2.7 and with genomes which still have their version numbers attached (e.g. NC_008253.1). It worked well on my example data, but not on the whole dataset.

The problem are apparently duplicated genes in the gene_presence_absence.csv table. In that table, a sample can have multiple gene IDs for one gene, separated by tabs. In the genomas_locus.csv, I then get multiple entries as well, like this:
NZ_CP027766.1|['NZ_CP027766.1_00163', 'NZ_CP027766.1_00164']
NZ_CP027766.1|['NZ_CP027766.1_00163', 'NZ_CP027766.1_00164']

I am not sure how to proceed with this. Did this happen in your analysis as well? You have the
```
else:
    print(locus)
    raise
```
lines in the get_locus_sequence() function, so maybe you were looking at this already?

Thanks!
@LilithElina

**Comment by LilithElina** [comment]
I am very sorry, this was actually my own fault.

In the original `get_genomas_locus()` function, you had the following lines:
```
else:  # tiene mas de un locus en esa celda
    for locus in loci:  # separalos!
        print('{}|{}'.format(genoma[0], locus), file=out_csv)
```
but `loci` didn't exist as a variable, so I changed that to `for loc in locus`. I forgot to change the print statement as well, though. That's why the genomas_locus.csv looked so weird, and why the same entry appeared multiple times.

**Comment by Katterinne** [comment]
Hello, I am sorry I did not answer before, I was on a trip with limited internet connection.
Anyway, I am glad you make it work.

Thank you and good luck with your analysis!
