### ISSUE TITLE
Interpretation of roary output

### ISSUE THREAD

**Issue by vappiah** [microgenomics/tutorials#8]
Hello All,
I would be grateful if you can interpret the attached image which is an output of your roary tutorial.
![pangenome_frequency-2](https://user-images.githubusercontent.com/14283733/115167562-aa2d2500-a0a7-11eb-951b-522941b724a0.png)

Especially with regards to the number of genomes and the corresponding genes. If lets say 2 genomes, which of the genomes does it refer to ? Do I assume it is an average ?

**Comment by ecastron** [comment]
Hello,

I believe Roary takes genomes in alphabetical order and performs the analysis. While I think the results will be dependent on the order, I don’t think the overall picture will vary much.

Cheers,

Eduardo

**Comment by vappiah** [comment]
Hi, Thanks for the response. I applied roary on my dataset.  And using your interpretation about the alphabetical order, I could still not interpret the frequency chart. I will post that question on the roary github page
